### PR TITLE
Added Escape to quit

### PR DESCRIPTION
**Pull request by osalbahr**
Press <ESC> at any time to exit the program

### CODE REVIEW

**Comment by EbbDrop** [comment]
This is nice for the desktop version. But just gives a black page on web. Maybe disable this functionality for web builds.

You can use `#[cfg(not(target_family = "wasm"))]` to disable a block of code on web.

**Comment by osalbahr** [comment]
Oh, that is interesting. I found documentation online about "#[cfg" online for something that looks like function decoration (at least that is what is called in python). I found documentation about the cfg macro, which seems to fit if statements. Much nicer than C's #ifdef's!

I accidentally created another PR but I am reopening this one, hopefully it updates to the last commit to this branch.

**Comment by EbbDrop** [comment]
This looks good.

You can also use `#[cfg(not(target_family = "wasm"))]` like this inside a function:
```rust
#[cfg(not(target_family = "wasm"))]
if is_key_down(KeyCode::Escape) {
    std::process::exit(0);
} 
```

**Comment by osalbahr** [comment]
Oh, I see, thank you for explaining. However since it is an else if the compiler did not like it. Although for this program the "else if" is superfluous.

**Pull request merged**
